# Generated by Django 3.0 on 2020-02-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_Number',
            field=models.CharField(default=None, max_length=25, primary_key=True, serialize=False),
        ),
    ]
