# Generated by Django 3.0 on 2020-02-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slug_for_Detail',
        ),
    ]
