# Generated by Django 3.0 on 2020-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_doctor_licence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_Number',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
    ]
