# Generated by Django 3.0.4 on 2020-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
