# Generated by Django 3.0 on 2020-02-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200215_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='short_Detail_of_Problem',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
