# Generated by Django 3.0 on 2020-02-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_patient_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='picture',
        ),
    ]
