# Generated by Django 3.0 on 2020-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200215_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='short_Detail_of_Problem',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
