# Generated by Django 3.0 on 2020-02-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200217_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='short_Detail_of_Problem',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
