# Generated by Django 3.0 on 2020-02-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
