# Generated by Django 2.2.6 on 2019-10-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character ISBN number. International Standard Book Number.', max_length=13, verbose_name='ISBN'),
        ),
        migrations.CreateModel(
            name='DonateBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=100)),
                ('author_of_book', models.CharField(max_length=100)),
                ('price_of_book', models.DecimalField(decimal_places=3, max_digits=10)),
                ('year_of_publication', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(help_text='Select a genre for this Boook', to='catalog.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language')),
            ],
            options={
                'ordering': ['name_of_book'],
            },
        ),
    ]
