# Generated by Django 3.0 on 2020-02-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ManyToManyField(default=None, to='catalog.Department'),
        ),
    ]
