# Generated by Django 2.2.6 on 2019-10-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191022_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatebooks',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='donatebooks',
            old_name='name_of_book',
            new_name='name',
        ),
    ]
