# Generated by Django 2.2.6 on 2019-10-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191022_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonateBooks',
        ),
    ]
