# Generated by Django 3.0 on 2020-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Pediatrics', 'Pediatrics'), ('Surgeon', 'Surgeon'), ('Physician', 'Physician'), ('aenocologist', 'Gaenocologist'), ('Dermatologist', 'Dermatologist'), ('Dentist', 'Dentist')], default='Physician', max_length=20),
        ),
    ]
