# Generated by Django 3.0 on 2020-02-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200214_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Pediatrics', 'Pediatrics'), ('Surgeon', 'Surgeon'), ('Physician', 'Physician'), ('Gaenocologist', 'Gaenocologist'), ('Dermatologist', 'Dermatologist'), ('Dentist', 'Dentist')], default='Physician', max_length=20, unique=True),
        ),
    ]
