# Generated by Django 2.2.6 on 2019-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='copies',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='donate',
            name='donator_name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
