# Generated by Django 2.2.6 on 2019-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20191024_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
