# Generated by Django 2.2.6 on 2019-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_donate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate_for_free',
            field=models.CharField(default='Yes', max_length=5),
        ),
    ]
