# Generated by Django 2.2.6 on 2019-11-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
