# Generated by Django 2.2.6 on 2019-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
