# Generated by Django 2.2.6 on 2019-11-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
