# Generated by Django 2.2.6 on 2019-11-17 13:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(default='Write the content of the blog here', max_length=10000),
        ),
        migrations.AddField(
            model_name='about',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(default='slug-title-as-this', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending Review'), (2, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Title', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='about',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='writer',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donate',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
