# Generated by Django 2.2.6 on 2019-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
