# Generated by Django 2.2.6 on 2019-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20191117_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='about',
            name='writer',
        ),
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.TextField(default='About', help_text='About the Website & Project', max_length=3500),
        ),
        migrations.AlterField(
            model_name='donate',
            name='copies',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
