# Generated by Django 2.2.6 on 2019-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20191117_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
