# Generated by Django 2.2.6 on 2019-11-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
