# Generated by Django 3.0 on 2020-02-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Disease', max_length=200)),
                ('type', models.CharField(choices=[('inf', 'Infectious'), ('def', 'Deficiency'), ('her', 'hereditary'), ('phy', 'Physiological'), ('non', 'None'), ('ud', 'Under Diagnosis')], default='non', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Doctor's name", max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender')], default='m', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Patient Name', max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender')], default='m', max_length=20)),
                ('disease_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.disease')),
                ('treatment_Under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
