# Generated by Django 2.2.6 on 2019-11-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_exam_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
