# Generated by Django 3.0 on 2020-02-13 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200213_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar_Number',
            field=models.UUIDField(default=uuid.uuid4, help_text='Patient AADHAR Card Number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(choices=[('inf', 'Infectious'), ('def', 'Deficiency'), ('her', 'Hereditary'), ('phy', 'Physiological'), ('non', 'None'), ('ud', 'Under Diagnosis')], default='non', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment_Under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Doctor'),
        ),
    ]
