# Generated by Django 2.2.6 on 2019-12-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
