# Generated by Django 3.0 on 2020-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254)),
                ('tenth_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('twelth_mark', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tenth_year', models.DateField(blank=True, null=True)),
                ('twelth_year', models.DateField(blank=True, null=True)),
                ('tenth_board', models.CharField(default='CBSE', help_text='Enter your Board name', max_length=20)),
                ('twelth_board', models.CharField(default='CBSE', help_text='Enter your 12th board Name', max_length=20)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default='Male', help_text="What's your Gender", max_length=20)),
            ],
        ),
    ]
