# Generated by Django 3.0 on 2020-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_predictor'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='interest',
            field=models.CharField(blank=True, choices=[('s', 'Science'), ('m', 'Math'), ('c', 'commerce')], default='s', help_text='In which stream you are Interested', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='subject_for_science',
            field=models.CharField(blank=True, choices=[('pcm', 'PCM'), ('pcb', 'PCB'), ('pcmb', 'PCMB'), ('no', 'NONE')], default='pcm', help_text='Select the subject combination', max_length=20),
        ),
    ]
