# Generated by Django 3.0 on 2020-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200206_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='subject_for_arts',
            field=models.CharField(blank=True, choices=[('history', 'HISTORY'), ('journalism', 'JOURNALISM'), ('english', 'ENGLISH'), ('politicalScience', 'POLITICAL SCIENCE'), ('geography', 'GEOGRAPHY'), ('no', 'NONE')], default='history', help_text='Select the subject for Arts', max_length=20),
        ),
    ]
