# Generated by Django 3.0 on 2020-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_predictor_subject_for_arts'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='subject_for_commerce',
            field=models.CharField(blank=True, choices=[('economics', 'ECONOMICS'), ('bussiness', 'BUSSINESS STUDIES'), ('accountancy', 'ACCOUNTANCY'), ('no', 'NONE')], default='no', help_text='Select the subject for Commerce', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='subject_for_arts',
            field=models.CharField(blank=True, choices=[('history', 'HISTORY'), ('journalism', 'JOURNALISM'), ('english', 'ENGLISH'), ('politicalScience', 'POLITICAL SCIENCE'), ('geography', 'GEOGRAPHY'), ('no', 'NONE')], default='no', help_text='Select the subject for Arts', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='subject_for_science',
            field=models.CharField(blank=True, choices=[('pcm', 'PCM'), ('pcb', 'PCB'), ('pcmb', 'PCMB'), ('no', 'NONE')], default='no', help_text='Select the subject combination', max_length=20),
        ),
    ]
