# Generated by Django 3.0 on 2020-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200206_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='extra_curriculum_activity',
            field=models.CharField(default='Mention, if you have any other extra curriculum activity.', max_length=5000),
        ),
        migrations.AddField(
            model_name='predictor',
            name='father_occupation',
            field=models.CharField(choices=[('govtService', 'GOVERNMENT SERVICE'), ('privateService', 'PRIVATE SERVICE'), ('agriculture', 'AGRICULTURE'), ('bussiness', 'BUSSINESS'), ('other', 'OTHER')], default='other', help_text="What is your Father's Occupation", max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='income_status',
            field=models.CharField(choices=[('high', 'HIGH(>1000000)'), ('medium', 'MEDIUM(500000-1000000)'), ('low', 'LOW(<500000)')], default='low', help_text="What is your Family's Income", max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='language_of_communication',
            field=models.CharField(default='Hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='predictor',
            name='mother_occupation',
            field=models.CharField(choices=[('govtService', 'GOVERNMENT SERVICE'), ('housewife', 'HOUSEWIFE'), ('privateService', 'PRIVATE SERVICE'), ('agriculture', 'AGRICULTURE'), ('bussiness', 'BUSSINESS'), ('other', 'OTHER')], default='housewife', help_text="What is your Father's Occupation", max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='scholarship_status',
            field=models.CharField(choices=[('yes', 'YES'), ('nope', 'NO')], default='nope', help_text='Do have any Scholarship', max_length=20),
        ),
    ]
