# Generated by Django 3.0 on 2020-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20200206_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='extra_curriculum_activity',
            field=models.TextField(default='Mention, if you have any other extra curriculum activity.', max_length=5000),
        ),
    ]
