# Generated by Django 3.0 on 2020-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20200206_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='interest',
            field=models.CharField(choices=[('s', 'Science'), ('m', 'Math'), ('c', 'commerce')], default='s', help_text='In which stream you are Interested', max_length=20),
        ),
    ]
