# Generated by Django 3.0 on 2020-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20200207_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='are_you_interested_in_agriculture',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Are you interested in agriculture ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='are_you_interested_to_work_with_different_culture_community_and_religions_across_the_country',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Are you interested to work with different culture,community & religions across the country ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_follow_rules_and_regulations_in_every_aspects_of_life',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you follow rules and regulations in every aspects of life ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_capacity_to_influence_and_persuading_people',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have capacity to influence and persuading people ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_curiosity_about_plants',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have curiosity about plants ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_deep_interest_in_Indian_constitution_IPC_CrPC_CPC_and_other_laws_of_India',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have deep interest in Indian constitution,IPC, CrPC,CPC & other laws of India ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_emotional_intelligence',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have emotional intelligence ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_interest_in_developing_sustainable_resources',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have interest in developing sustainable resources ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_interest_in_indian_history_and_politics',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have interest in indian history and politics ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_have_interest_in_marketing',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you have interest in marketing ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_take_interest_in_planning_and_organizing_activity_of_others',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you take interest in planning and organizing activity of others ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_want_to_work_with_business_people',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you want to work with business people ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='do_you_want_to_work_with_those_who_have_lost_their_direction',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], default='notMuch', help_text='Do you want to work with those who have lost their direction ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='how_many_hours_would_you_like_to_work_in_a_week',
            field=models.CharField(choices=[('work1', 'Not more than 40 hours.'), ('work2', 'Not more than 48 hours.'), ('work3', 'Not more than 32 hours.'), ('work4', 'Number of hours required according to work requirement.')], default='work1', help_text='How many hours would you like to work in a week ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='you_want_to_be',
            field=models.CharField(choices=[('entrepreneur', 'An Entrepreneur'), ('mnc', 'An Employee of a Multi National Company'), ('govt', 'A Government Servant'), ('social', 'Social Worker')], default='mnc', help_text='You want to be _________.', max_length=25),
        ),
    ]
