# Generated by Django 3.0 on 2020-02-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200207_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='author',
        ),
        migrations.AlterField(
            model_name='predictor',
            name='tenth_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='twelth_year',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
