# Generated by Django 3.0 on 2020-02-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20200207_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donate',
        ),
    ]
