# Generated by Django 3.0 on 2020-02-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_delete_donate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
