# Generated by Django 3.0 on 2020-02-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20200207_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictor',
            old_name='do_you_take_interest_in_planning_and_organizing_activity_of_others',
            new_name='interest_in_planning_and_organizing_activity_of_others',
        ),
    ]
