# Generated by Django 3.0 on 2020-02-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20200207_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='are_you_interested_to_work_with_different_culture_community_and_religions_across_the_country',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='culture_and_community', default='notMuch', help_text='Are you interested to work with different culture,community & religions across the country ?', max_length=25),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='do_you_follow_rules_and_regulations_in_every_aspects_of_life',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='rules_and_regulation', default='notMuch', help_text='Do you follow rules and regulations in every aspects of life ?', max_length=25),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='do_you_have_deep_interest_in_Indian_constitution_IPC_CrPC_CPC_and_other_laws_of_India',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='constitution', default='notMuch', help_text='Do you have deep interest in Indian constitution,IPC, CrPC,CPC & other laws of India ?', max_length=25),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='interest_in_planning_and_organizing_activity_of_others',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='planning_and_organizing', default='notMuch', help_text='Do you take interest in planning and organizing activity of others ?', max_length=25),
        ),
    ]
