# Generated by Django 3.0 on 2020-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20200207_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='are_you_interested_to_work_with_different_culture_community_and_religions_across_the_country',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='do_you_follow_rules_and_regulations_in_every_aspects_of_life',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='do_you_have_deep_interest_in_Indian_constitution_IPC_CrPC_CPC_and_other_laws_of_India',
        ),
        migrations.AddField(
            model_name='predictor',
            name='follow_rules_and_regulations_in_every_aspects_of_life',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='rules_and_regulation', default='notMuch', help_text='Follow rules and regulations in every aspects of life ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='interest_in_Indian_constitution_IPC_CrPC_CPC_and_other_law',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='constitution', default='notMuch', help_text='Interest in Indian constitution,IPC, CrPC,CPC & other law ?', max_length=25),
        ),
        migrations.AddField(
            model_name='predictor',
            name='interested_with_community_and_religions_across_the_country',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('notMuch', 'NOT MUCH')], db_column='culture_and_community', default='notMuch', help_text='Interested with different community & religions across the country ?', max_length=25),
        ),
    ]
